export const LOAD_USERS='LOAD_USERS';
export const LOAD_USERS_SUCCESS='LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE='LOAD_USERS_FAILURE';

export const SELECTED_USER_DETAILS='SELECTED_USER_DETAILS';
export const SELECTED_USER_DETAILS_SUCCESS='SELECTED_USER_DETAILS_SUCCESS';
export const SELECTED_USER_DETAILS_FAILURE='SELECTED_USER_DETAILS_FAILURE';

